name: Craw And Update

on:
  schedule:
    - cron: '0 24 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  craw:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Requirements
      run: |
        pip install -r requirements.txt

    - name: Start Craw
      run: |
        python main.py

    - name: Commit
      run: |
        git config --global user.email bot@rdpstudio.top
        git config --global user.name RDPStudio Bot
        git add .
        git commit -m "Update"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
